apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-api
  name: spring-boot-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: app
  selector:
    app: spring-boot-api