apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-api
  labels:
    app: spring-boot-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: spring-boot-api
  template:
    metadata:
      labels:
        app: spring-boot-api
    spec:
      containers:
        - image: pnowy/spring-boot-api:latest
          imagePullPolicy: Always
          name: spring-boot-api
          readinessProbe:
            httpGet:
              port: app
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              port: app
              path: /actuator/health/ping
            initialDelaySeconds: 20
          ports:
            - containerPort: 8080
              name: app
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-api
  name: spring-boot-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: app
  selector:
    app: spring-boot-api